#!/bin/bash

# bail early if .taskId is absent or empty
[ -s .taskId ] || exit 0

source $HOME/.cw/default # ASSUMING this file exists on host

# read taskID into a var
TASK_ID=$( < .taskId )

# read commit message into a var
COMMIT_MSG=$( < $1 )

# write the new commit message
cat << EOT > $1
$TASK_ID - $COMMIT_MSG

${CWCLI_TASK_URL_PREFIX}${TASK_ID}
EOT
